added mechanism to export s3 link in export csv
AIcrowd/AIcrowd pull request #1696
Opened 2020-10-13 15:27 UTC by Shriyanshagro

2020-10-14 06:41 UTC, skbly7 requested changes

2020-10-14 06:41 UTC, skbly7 commented on app/services/submissions/csv_export_service.rb
> +            links = []
consider empty case

2020-10-14 06:41 UTC, skbly7 commented on app/services/submissions/csv_export_service.rb
> +          if downloadable & submission.submission_files.present?
& -> &&

2020-10-14 06:41 UTC, skbly7 commented on spec/services/submissions/csv_export_service_spec.rb
>    let!(:submissions)     { create_list(:submission, 3, participant: participant, challenge_round: challenge_round) }
`:with_file` can be tried

2020-10-15 04:53 UTC, Shriyanshagro commented on app/services/submissions/csv_export_service.rb
> +            links = []
done

2020-10-15 04:53 UTC, Shriyanshagro commented on app/services/submissions/csv_export_service.rb
> +          if downloadable & submission.submission_files.present?
not required anymore

2020-10-15 05:39 UTC, Shriyanshagro commented on spec/services/submissions/csv_export_service_spec.rb
>    let!(:submissions)     { create_list(:submission, 3, participant: participant, challenge_round: challenge_round) }
done

2020-10-15 05:40 UTC, Shriyanshagro commented on app/services/base_service.rb
> +  def s3_expiring_url(s3_key)
resolved

2020-10-15 12:11 UTC, skbly7 approved these changes

2020-10-18 07:57 UTC, merged