Tech 376
AIcrowd/AIcrowd pull request #1886
Opened 2021-04-12 18:09 UTC by sujnesh

2021-04-13 11:49 UTC, skbly7 requested changes

2021-04-13 11:49 UTC, skbly7 commented on app/controllers/submissions_controller.rb
> +      redirect_to @challenge,
`redirect_or_json` need to be used

2021-04-13 11:49 UTC, skbly7 commented on app/controllers/concerns/challenge_masthead.rb
> +        before_action :redirect_if_hidden, only: actions
Not sure why it is here? Should it be part of Discussions controller?

2021-04-22 12:12 UTC, skbly7 commented on app/policies/challenge_policy.rb
> +    team = participant.teams.where(challenge_id: @record.id).first
what if there is no team?

2021-04-22 12:12 UTC, sujnesh commented on app/policies/challenge_policy.rb
> +    team = participant.teams.where(challenge_id: @record.id).first
Will break if no team

2021-04-22 12:13 UTC, skbly7 commented on app/policies/challenge_policy.rb
> +    team = participant.teams.where(challenge_id: @record.id).first
```
if team.present?
    participants = team.team_participants.map(&:participant) if team.present?
    participants = [participant] if participants.blank?
    return participants.count
end
return 1
```

2021-04-22 12:14 UTC, skbly7 approved these changes

2021-04-22 18:26 UTC, merged